//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSewApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesSew : DbContext
    {
        public EntitiesSew()
            : base("name=EntitiesSew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ЕдИзмерения> ЕдИзмерения { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<ЗаказанныеИзделия> ЗаказанныеИзделия { get; set; }
        public virtual DbSet<Изделия_> Изделия_ { get; set; }
        public virtual DbSet<ИзмерениеНоменклатуры> ИзмерениеНоменклатуры { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Роль> Роль { get; set; }
        public virtual DbSet<СкладТкани> СкладТкани { get; set; }
        public virtual DbSet<СкладФурнитуры> СкладФурнитуры { get; set; }
        public virtual DbSet<Ткани_> Ткани_ { get; set; }
        public virtual DbSet<ТканиИзделия> ТканиИзделия { get; set; }
        public virtual DbSet<Фурнитура_> Фурнитура_ { get; set; }
        public virtual DbSet<ФурнитураИзделия> ФурнитураИзделия { get; set; }
        public virtual DbSet<ЭтапВыполнения> ЭтапВыполнения { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
