//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSewApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИзмерениеНоменклатуры
    {
        public int Номер { get; set; }
        public string Номенклатура { get; set; }
        public string ЕдиницаИзмерения { get; set; }
        public bool Основная { get; set; }
    
        public virtual ЕдИзмерения ЕдИзмерения { get; set; }
        public virtual Ткани_ Ткани_ { get; set; }
        public virtual Фурнитура_ Фурнитура_ { get; set; }
    }
}
