//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSewApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class СкладТкани
    {
        public string Рулон { get; set; }
        public string Ткань { get; set; }
        public int Ширина { get; set; }
        public int Длина { get; set; }
        public Nullable<double> Списано { get; set; }
    
        public virtual Ткани_ Ткани_ { get; set; }
    }
}
