//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSewApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТканиИзделия
    {
        public int Номер { get; set; }
        public string Ткань { get; set; }
        public string Изделиe { get; set; }
    
        public virtual Изделия_ Изделия_ { get; set; }
        public virtual Ткани_ Ткани_ { get; set; }
    }
}
