//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfSewApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ФурнитураИзделия
    {
        public int Номер { get; set; }
        public string Фурнитура { get; set; }
        public string Изделие { get; set; }
        public string Размещение { get; set; }
        public Nullable<int> Ширина { get; set; }
        public Nullable<int> Длинна { get; set; }
        public Nullable<int> Поворот { get; set; }
        public int Количество { get; set; }
    
        public virtual Изделия_ Изделия_ { get; set; }
        public virtual Фурнитура_ Фурнитура_ { get; set; }
    }
}
